steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: build-if-tag-created
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "northamerica-northeast1-docker.pkg.dev/${PROJECT_ID}/tb-project/rstudio" > /workspace/imagename
        image=$(cat /workspace/imagename)
        docker build -t $image .
  - name: 'gcr.io/cloud-builders/docker'
    id: push-if-tag-created
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        image=$(cat /workspace/imagename)
        docker push $image
        
